dsadd user "CN=TESTPHS TESTPHS,OU=2016,OU=PHS,DC=portage,DC=k12,DC=wi,DC=us" -fn TESTPHS -ln TESTPHS -samid TESTPHS -display "TESTPHS TESTPHS" -pwd password -email TESTPHS@portage.k12.wi.us  -upn TESTPHS@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=HS-Stud-No-Sync,OU=PHS,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\phs-fs.portage.k12.wi.us\homeDir-PHS\Students\2016\TESTPHS -hmdrv h: -desc "2016 4/15/2014"

dsadd user "CN=TESTBMS TESTBMS,OU=Student,OU=BMS,DC=portage,DC=k12,DC=wi,DC=us" -fn TESTBMS -ln TESTBMS -samid TESTBMS -display "TESTBMS TESTBMS" -pwd password -email TESTBMS@portage.k12.wi.us  -upn TESTBMS@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-BMS-WGM,OU=BMS,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\bms-dc01.portage.k12.wi.us\homeDir\Students\2018\TESTBMS -hmdrv h: -desc "2018 4/15/2014"

dsadd user "CN=TESTRUSCH TESTRUSCH,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn TESTRUSCH -ln TESTRUSCH -samid TESTRUSCH -display "TESTRUSCH TESTRUSCH" -pwd password -email TESTRUSCH@portage.k12.wi.us  -upn TESTRUSCH@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\TESTRUSCH -hmdrv h: -desc "2022 4/15/2014"

dsadd user "CN=TESTMUIR TESTMUIR,OU=2023,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn TESTMUIR -ln TESTMUIR -samid TESTMUIR -display "TESTMUIR TESTMUIR" -pwd password -email TESTMUIR@portage.k12.wi.us  -upn TESTMUIR@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\Students\TESTMUIR -hmdrv h: -desc "2023 4/15/2014"

dsadd user "CN=FAC MUIR,OU=Faculty,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn FAC -ln MUIR -samid FACTESTMUIR -display "FAC MUIR" -pwd password -email FACTESTMUIR@portage.k12.wi.us  -upn FACTESTMUIR@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=FAC-NO-SYNC-MUIR,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\Faculty\FACTESTMUIR -hmdrv h: -desc "Teacher 6/1/14"

dsadd user "CN=FAC RUSCH,OU=R-Faculty,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn FAC -ln RUSCH -samid FACTESTRUSCH -display "FAC RUSCH" -pwd password -email FACTESTRUSCH@portage.k12.wi.us  -upn FACTESTRUSCH@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Fac-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Faculty\FACTESTRUSCH -hmdrv h: -desc "Teacher 6/1/14"

dsadd user "CN=FAC PHS,OU=Faculty,OU=PHS,DC=portage,DC=k12,DC=wi,DC=us" -fn FAC -ln PHS -samid FACTTESTPHS -display "FAC PHS" -pwd password -email FACTTESTPHS@portage.k12.wi.us  -upn FACTTESTPHS@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=HS-Fac-No-Sync,OU=PHS,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\phs-fs.portage.k12.wi.us\homeDir-PHS\Faculty\FACTTESTPHS -hmdrv h: -desc "Athletic Director 7/1/14"

