dsadd user "CN=Mason Bolgrien,OU=2023,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Mason -ln Bolgrien -samid bolgrmas -display "Mason Bolgrien" -pwd 2560asdf -email bolgrmas@portage.k12.wi.us  -upn bolgrmas@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\bolgrmas -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Keyera Carlson,OU=2023,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Keyera -ln Carlson -samid carlskey -display "Keyera Carlson" -pwd 2479asdf -email carlskey@portage.k12.wi.us  -upn carlskey@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\carlskey -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Nathan Cohee,OU=2023,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Nathan -ln Cohee -samid coheenat -display "Nathan Cohee" -pwd 2649asdf -email coheenat@portage.k12.wi.us  -upn coheenat@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\coheenat -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Blake Fry,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Blake -ln Fry -samid frybla -display "Blake Fry" -pwd 8767asdf -email frybla@portage.k12.wi.us  -upn frybla@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\frybla -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Aspen Hays,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Aspen -ln Hays -samid haysasp -display "Aspen Hays" -pwd 2364asdf -email haysasp@portage.k12.wi.us  -upn haysasp@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\haysasp -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Katherine Mills,OU=2023,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Katherine -ln Mills -samid millskat -display "Katherine Mills" -pwd 2295asdf -email millskat@portage.k12.wi.us  -upn millskat@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\millskat -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Jocelyn Naxi,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Jocelyn -ln Naxi -samid naxijoc -display "Jocelyn Naxi" -pwd 2145asdf -email naxijoc@portage.k12.wi.us  -upn naxijoc@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\naxijoc -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Noah Nollenberg,OU=2023,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Noah -ln Nollenberg -samid nollenoa -display "Noah Nollenberg" -pwd 2423asdf -email nollenoa@portage.k12.wi.us  -upn nollenoa@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\nollenoa -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Meygen Schlieve,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Meygen -ln Schlieve -samid schlimey -display "Meygen Schlieve" -pwd 3932asdf -email schlimey@portage.k12.wi.us  -upn schlimey@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\schlimey -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Anastazia Scott,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Anastazia -ln Scott -samid scottana -display "Anastazia Scott" -pwd 2586asdf -email scottana@portage.k12.wi.us  -upn scottana@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\scottana -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Timothy Scott,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Timothy -ln Scott -samid scotttim -display "Timothy Scott" -pwd 3095asdf -email scotttim@portage.k12.wi.us  -upn scotttim@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\scotttim -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Hayden Steinle,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Hayden -ln Steinle -samid steinhay -display "Hayden Steinle" -pwd 2249asdf -email steinhay@portage.k12.wi.us  -upn steinhay@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\steinhay -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Tanner Taft,OU=2023,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Tanner -ln Taft -samid tafttan -display "Tanner Taft" -pwd 2121asdf -email tafttan@portage.k12.wi.us  -upn tafttan@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\tafttan -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Vaughn Tofson,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Vaughn -ln Tofson -samid tofsovau -display "Vaughn Tofson" -pwd 2166asdf -email tofsovau@portage.k12.wi.us  -upn tofsovau@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\tofsovau -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Mason Treinen,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Mason -ln Treinen -samid treinmas -display "Mason Treinen" -pwd 8325asdf -email treinmas@portage.k12.wi.us  -upn treinmas@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\treinmas -hmdrv h: -desc "2022 3/6/14"

dsadd user "CN=Molly Voigt,OU=2022,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Molly -ln Voigt -samid voigtmol -display "Molly Voigt" -pwd 2303asdf -email voigtmol@portage.k12.wi.us  -upn voigtmol@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\voigtmol -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Nikita Yost,OU=2023,OU=Student,ou=Muir,DC=portage,DC=k12,DC=wi,DC=us" -fn Nikita -ln Yost -samid yostnik -display "Nikita Yost" -pwd 2694asdf -email yostnik@portage.k12.wi.us  -upn yostnik@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Stud-Group-for-Muir-WGM,OU=Muir,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\muir-dc01.portage.k12.wi.us\homeDir\yostnik -hmdrv h: -desc "2023 6/16/14"
