dsadd user "CN=Jerimiah Bey,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Jerimiah -ln Bey -samid beyjer -display "Jerimiah Bey" -pwd 7435asdf -email beyjer@portage.k12.wi.us  -upn beyjer@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\beyjer -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Kali Broesch,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Kali -ln Broesch -samid broeskal -display "Kali Broesch" -pwd 6221asdf -email broeskal@portage.k12.wi.us  -upn broeskal@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\broeskal -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Brody Buettner,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Brody -ln Buettner -samid buettbro -display "Brody Buettner" -pwd 8989asdf -email buettbro@portage.k12.wi.us  -upn buettbro@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\buettbro -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Koby Buettner,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Koby -ln Buettner -samid buettkob -display "Koby Buettner" -pwd 2167asdf -email buettkob@portage.k12.wi.us  -upn buettkob@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\buettkob -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Courtney Chambers,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Courtney -ln Chambers -samid chambcou -display "Courtney Chambers" -pwd 9426asdf -email chambcou@portage.k12.wi.us  -upn chambcou@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\chambcou -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Kayden Christian,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Kayden -ln Christian -samid chriskay -display "Kayden Christian" -pwd 9587asdf -email chriskay@portage.k12.wi.us  -upn chriskay@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\chriskay -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Bethany Krumpos,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Bethany -ln Krumpos -samid krumpbet -display "Bethany Krumpos" -pwd 2569asdf -email krumpbet@portage.k12.wi.us  -upn krumpbet@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\krumpbet -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Allison Monfort,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Allison -ln Monfort -samid monfoall -display "Allison Monfort" -pwd 1955asdf -email monfoall@portage.k12.wi.us  -upn monfoall@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\monfoall -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Jeremy Saloun,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Jeremy -ln Saloun -samid saloujer -display "Jeremy Saloun" -pwd 2823asdf -email saloujer@portage.k12.wi.us  -upn saloujer@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\saloujer -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Greta Shortreed,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Greta -ln Shortreed -samid shortgre -display "Greta Shortreed" -pwd 2566asdf -email shortgre@portage.k12.wi.us  -upn shortgre@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\shortgre -hmdrv h: -desc "2023 6/16/14"

dsadd user "CN=Faith Simonson,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Faith -ln Simonson -samid simonfai -display "Faith Simonson" -pwd 2297asdf -email simonfai@portage.k12.wi.us  -upn simonfai@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\simonfai -hmdrv h: -desc "2022 6/16/14"

dsadd user "CN=Jacob Zajicek,OU=R-Student,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us" -fn Jacob -ln Zajicek -samid zajicjac -display "Jacob Zajicek" -pwd 2343asdf -email zajicjac@portage.k12.wi.us  -upn zajicjac@portage.k12.wi.us -disabled no -canchpwd no -pwdneverexpires yes -memberof CN=Rusch-Stud-No-Sync,OU=RUSCH,DC=portage,DC=k12,DC=wi,DC=us -hmdir \\rusch-dc01.portage.k12.wi.us\homeDir-Rusch\Students\zajicjac -hmdrv h: -desc "2022 6/16/14"
